services:
  api-grafos:
    build:
      context: ./grafo_api
      dockerfile: conf/env/docker/Dockerfile
    volumes:
      - ./grafo_api/app:/app/app
#      - ./grafo_api/alembic/alembic.ini:/app/alembic.ini
#      - ./grafo_api/alembic/alembic/:/app/alembic/
    environment:
      PYTHONPATH: /app
    ports:
      - "8010:8000"
    networks:
      - grafos_network
    restart: unless-stopped


networks:
  grafos_network:
    driver: bridge
    attachable: true
