services:
  api-grafos:
    build:
      context: ./grafo_api
      dockerfile: conf/env/docker/Dockerfile
    environment:
      PYTHONPATH: /app
    ports:
      - "8010:8000"
    networks:
      - grafos_network

  front-end-grafos:
    build:
      context: ./front-end
      dockerfile: conf/env/docker/Dockerfile
    ports:
      - "5177:80"
    networks:
      - grafos_network
    restart: unless-stopped

networks:
  grafos_network:
    driver: bridge
    attachable: true
