services:
services:
  api-grafos:
    build:
      context: ./grafo_api  # Contexto agora é a pasta grafo_api
      dockerfile: conf/env/docker/Dockerfile
    environment:
      PYTHONPATH: /app:/app/grafo_backend  # Caminho explícito
    ports:
      - "8010:8000"
    networks:
      - grafos_network
    restart: unless-stopped


networks:
  grafos_network:
    driver: bridge
    attachable: true
