services:
  api-grafos:
    build:
      context: ./grafo_api
      dockerfile: conf/env/docker/Dockerfile
    environment:
      PYTHONPATH: /app
    ports:
      - "8010:8000"
    networks:
      - grafos_network


networks:
  grafos_network:
    driver: bridge
    attachable: true
